---
linters:
    flake8:
    eslint:
        config: '../.eslintrc.json'
    csslint:

fixers:
    enable: true

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
        - 'css/normalize.css'
        - 'js/init.js'
